version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.development
    volumes:
      - .:/app
    ports:
      - '27081:80'
    container_name: wxcloud_huaxia
    labels:
      - wxPort=27082
      - hostPort=27081
      - wxcloud=huaxia
      - role=container
    environment:
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=root
      - MYSQL_ADDRESS=127.0.0.1:3306
networks:
  default:
    external:
      name: wxcb0
